import { Injectable } from '@angular/core';
import { addIcons } from 'ionicons';
import {
  chevronDown,
  chevronUp,
  locationOutline,
  searchOutline,
  arrowBackOutline,
  arrowForwardOutline,
  heartOutline,
  heart,
  cashOutline,
  logoFacebook,
  logoInstagram,
  logoLinkedin,
  logoTiktok,
  logoYoutube,
  mailOutline,
  lockClosedOutline,
  alertCircleOutline,
  personCircleOutline,
  pinOutline,
  funnelOutline,
  listOutline,
  gridOutline,
  pricetagOutline,
  chevronForwardOutline,
  chevronBackOutline,
  createOutline,
  logOutOutline,
  personOutline,
  chatbubblesOutline,
  chatbubbleOutline,
  informationCircleOutline,
  shareOutline,
  map,
} from 'ionicons/icons';

@Injectable({ providedIn: 'root' })
export class IconService {
  registerIcons() {
    addIcons({
      'chevron-down-outline': chevronDown,
      'chevron-up-outline': chevronUp,
      'location-outline': locationOutline,
      'search-outline': searchOutline,
      'arrow-back-outline': arrowBackOutline,
      'arrow-forward-outline': arrowForwardOutline,
      'heart-outline': heartOutline,
      heart: heart,
      'cash-outline': cashOutline,
      'logo-facebook': logoFacebook,
      'logo-instagram': logoInstagram,
      'logo-linkedin': logoLinkedin,
      'logo-tiktok': logoTiktok,
      'logo-youtube': logoYoutube,
      'mail-outline': mailOutline,
      'lock-closed-outline': lockClosedOutline,
      'alert-circle-outline': alertCircleOutline,
      'person-circle-outline': personCircleOutline,
      'pin-outline': pinOutline,
      'funnel-outline': funnelOutline,
      'list-outline': listOutline,
      'grid-outline': gridOutline,
      'pricetag-outline': pricetagOutline,
      'chevron-forward-outline': chevronForwardOutline,
      'chevron-back-outline': chevronBackOutline,
      'create-outline': createOutline,
      'log-out-outline': logOutOutline,
      'person-outline': personOutline,
      'chatbubbles-outline': chatbubblesOutline,
      'chatbubble-outline': chatbubbleOutline,
      'information-circle-outline': informationCircleOutline,
      'logo-x': '/assets/icons/x.svg',
      'share-outline': shareOutline,
      breed: '/assets/icons/breed.svg',
      gender: '/assets/icons/gender.svg',
      color: '/assets/icons/color.svg',
      age: '/assets/icons/age.svg',
      height: '/assets/icons/height.svg',
      map: map,
    });
  }
}
